### ISSUE TITLE
主界面设置最上

### ISSUE THREAD

**Issue by FreeVB** [yjk282/Weather#2]
很漂亮的工具！这是我找到并开源的最好的了。
请问能加一个设置为置顶功能吗？就是主窗口放在最上层，这样就不会被别的窗口挡住了。

(还有，如果日历详情打开的时候，是无法退出的。)

**Comment by FreeVB** [comment]
找到了，在WindowHelper.cs里面可以设置。

**Comment by yjk282** [comment]
我的想法是日历应该放在最底层作为一个背景使用。

弹出窗口时无法退出是BUG。

**Comment by yjk282** [comment]
已修复

主窗口已置底
修复退出BUG
